name: QA Automation CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'tests/**'
      - 'src/**'
      - 'requirements.txt'
      - 'pytest.ini'
      - '.github/workflows/**'

  push:
    branches: [main]
    paths:
      - 'tests/**'
      - 'src/**'
      - 'requirements.txt'
      - 'pytest.ini'
      - '.github/workflows/**'

  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:
    inputs:
      suite:
        description: 'Suite to run'
        required: true
        default: 'smoke'

jobs:
  tests:
    runs-on: ubuntu-22.04

    environment: secure-qa-automation-platform-env
    env:
      # UI
      BASE_URL: ${{ secrets.BASE_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      LOCKEDUSER: ${{ secrets.LOCKEDUSER }}
      PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
      FIRSTNAME: ${{ secrets.FIRSTNAME }}
      LASTNAME: ${{ secrets.LASTNAME }}
      ZIP: ${{ secrets.ZIP }}
      PAYMENT_INFO: ${{ secrets.PAYMENT_INFO }}

      # API
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      USERNAME_API: ${{ secrets.USERNAME_API }}
      PASSWORD_API: ${{ secrets.PASSWORD_API }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Debug env (safe)
        run: |
          echo "Username exists? ${{ secrets.USERNAME != '' }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run scheduled smoke tests
        if: github.event_name == 'schedule'
        run: pytest -m smoke -v

      - name: Run manual selected suite
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.suite }}" = "smoke" ]; then
            pytest -m smoke -v
          elif [ "${{ github.event.inputs.suite }}" = "api" ]; then
            pytest tests/api -v
          elif [ "${{ github.event.inputs.suite }}" = "ui" ]; then
            pytest tests/ui -v
          else
            pytest -v
          fi

      - name: Run CI suite for push and pull request
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: pytest -m "not db" -v

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          if-no-files-found: ignore
          path: |
            allure-results
            reports
            screenshots